# 全局默认配置

# 训练参数
train:
  name: exp            # 实验名称
  epochs: 100
  batch_size: 16
  img_size: 640
  lr: 0.001
  device: cuda:0

  # 预处理（关键：使用 letterbox）
  letterbox: true

  # 优化器
  optimizer: Adam
  weight_decay: 0.0005

  # 学习率调度
  scheduler: cosine
  lr_min: 1e-6

  use_ema: True
  mosaic: True
  mosaic_disable_epoch: 10

# 验证参数
val:
  conf: 0.25
  iou: 0.45
  img_size: 640
  letterbox: true

# 推理参数
predict:
  conf: 0.25
  iou: 0.45
  img_size: 640
  letterbox: true
